### ISSUE TITLE
Compilation error: Supertypes of the following classes cannot be resolved

### ISSUE THREAD

**Issue by tony-gk** [Lipen/kotlin-satlib#13]
Code to reproduce:
```
fun main() {
    with(MiniSatSolver()) {
        val array = newBoolVarArray()
        println(array[0])
    }
}
```

The code above fails at compile time with the following error:
```
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.github.lipen.satlib.core.BoolVarArray, unresolved supertypes: com.github.lipen.multiarray.MultiArray
```

**Comment by Lipen** [comment]
We have to change `implementation` to `api` for MultiArray dependency [here](https://github.com/Lipen/kotlin-satlib/blob/master/core/build.gradle.kts#L7) (similar to `:jni`, actually). Can you make a PR?
I'm not completely sure that this is correct, but it will do for now.

Another fix is to manually add a MultiArray dependency on the client side. Note that even `compileOnly`-dep will be enough here (since `kotlin-satlib:core` already provides MultiArray in runtime), but it is better to use a standard `implementation`-dep. But I agree that it is better to fix it on our side.
